services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=productos_db
    volumes:
      - mysql_data:/var/lib/mysql
    
  app:
    build: .
    container_name: app
    restart: on-failure
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/productos_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

volumes:
  mysql_data: